### ISSUE TITLE
deep imports

### ISSUE THREAD

**Issue by medfx** [ng-turkey/ngxs-reset-plugin#24]
Hi guys,

After updating to Angular 9.1.0 I'm getting the following warning while compiling my app:

`Warning: Entry point 'ngxs-reset-plugin' contains deep imports into '.../node_modules/@ngxs/store/src/internal/internals'. This is probably not a problem, but may cause the compilation of ent
ry points to be out of order.`

ngxs-reset-plugin 1.2.0
ngxs/store 3.6.2

I have no idea about what this warning is actually saying. Just wanted to let you know. :-)

**Comment by salazarr-js** [comment]
same here 🤚🏼, before updating and trying a `ng build --prod`, I got the same warning

`Warning: Entry point 'ngxs-reset-plugin' contains deep imports into '.../node_modules/@ngxs/store/src/internal/internals'. This is probably not a problem, but may cause the compilation of entry points to be out of order.`

```
Angular CLI: 9.1.0
Node: 12.16.1
OS: darwin x64

Angular: 9.1.0
... animations, cli, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router
Ivy Workspace: Yes

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.901.0
@angular-devkit/build-angular     0.901.0
@angular-devkit/build-optimizer   0.901.0
@angular-devkit/build-webpack     0.901.0
@angular-devkit/core              9.1.0
@angular-devkit/schematics        9.1.0
@angular/cdk                      9.2.0
@angular/material                 9.2.0
@ngtools/webpack                  9.1.0
@schematics/angular               9.1.0
@schematics/update                0.901.0
rxjs                              6.5.4
typescript                        3.8.3
webpack                           4.42.0
```

**Comment by armanozak** [comment]
Hi @medfx, Hi @salazarr-js,

Thanks for the info. 

v1.2 was not supporting Angular 9.
v1.3 does and is published today. 🎉

I hope you enjoy using the plugin. Please let us know if you discover anything else.

Have a nice day.

**Comment by salazarr-js** [comment]
just update it today, and everything works perfect, thanks for all the work 🍻
