### ISSUE TITLE
If we are using StateReset for states which dont have values set, we are getting error 'split' of null from ngxs-store.js

### ISSUE THREAD

**Issue by arun-s-aot** [ng-turkey/ngxs-reset-plugin#42]
**Describe the bug**
I need to clear all the store datas (even datas which are stored in storagePlugins) whenever a new version of our application is deployed. So i tried to use **StateResetAll**  for clearing all the store datas. But as some of the stores were saved using storage plugin, i was not able to clear the datas fully. So i used **StateReset(<State1>,<State2>)** to it. I have total of 15 states to be cleared. There are chances where some states might not be having data when trying to update the app . In that case , i am getting an error as **property 'split' of null** from ngxs-store . The split value got in that function is coming as null at some places where my particular state is not assigned with any value . For other states with value, there is no issue. 

**Expected behavior**
Even if i pass a State without values, it should be null checked and then only passed to ngxs-store so that the sequence of execution of state reset wont break . 

**Screenshots**
![image](https://user-images.githubusercontent.com/49640066/109268617-2ef27580-77c0-11eb-8894-3852b3eb5d53.png)
![image](https://user-images.githubusercontent.com/49640066/109268711-51848e80-77c0-11eb-9673-dfa91ea107b1.png)
![image](https://user-images.githubusercontent.com/49640066/109268783-6b25d600-77c0-11eb-8028-157d95190dc8.png)

**Additional context**
I tried calling each State Clear seperately instead of
this.store.dispatch(new StateReset(<State1>,<State2>))
as 
this.store.dispatch(new StateReset(<State1>))
this.store.dispatch(new StateReset(<State2>))

Still same issue persists. 

Can you please work on it as we need to take a production build with these changes as its a critical part in clearing the data and providing user a fresh experience .  @armanozak  @denizguzel

**Comment by armanozak** [comment]
Hi,

Could you please share a minimum representation of the issue? A [StackBlitz](https://stackblitz.com/) or [CodeSandbox](https://codesandbox.io/) playground maybe?

**Comment by mzernetsch** [comment]
Encountered the same problem. It happens anytime you try to trigger a reset and exclude a state that has not been loaded yet:
https://stackblitz.com/edit/ngxs-repro-1tu8fj?file=src%2Fapp%2Fapp.component.ts

In my case this happens because the relevant state resides inside a lazy loaded page which is not always loaded before the user triggers a logout.

**Comment by armanozak** [comment]
Hi @mzernetsch,

Thanks for the feedback.

Well, that is expected behavior. Nevertheless, for a better DX, we could handle these cases. So, I've worked on it. There is an open PR. We will release a new version as soon as it is in.
