### ISSUE TITLE
Angular 13 compatibility

### ISSUE THREAD

**Issue by dmitry-salnikov** [ng-turkey/ngxs-reset-plugin#69]
Could you please update library dependencies to be compatible with Angular 13?

**Comment by armanozak** [comment]
Hi @dmitry-salnikov,

We have updated the library to be compatible with Angular 13 and released v2.0.0. Have you checked it? Is there a problem with that release?

**Comment by dmitry-salnikov** [comment]
Hi @armanozak,

Yes, I'm trying to install plugin and getting the next output in terminal:

```
$ npm i ngxs-reset-plugin@2.0.0
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR! 
npm ERR! While resolving: galaxy@0.0.1
npm ERR! Found: @angular/core@13.1.3
npm ERR! node_modules/@angular/core
npm ERR!   @angular/core@"13.1.3" from the root project
npm ERR!   peer @angular/core@">=12.0.0" from ngxs-reset-plugin@2.0.0
npm ERR!   node_modules/ngxs-reset-plugin
npm ERR!     ngxs-reset-plugin@"*" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer @angular/core@">=6.1.0 <13.0.0" from @ngxs/store@3.7.2
npm ERR! node_modules/@ngxs/store
npm ERR!   @ngxs/store@"3.7.2" from the root project
npm ERR!   peer @ngxs/store@">=0.0.0" from ngxs-reset-plugin@2.0.0
npm ERR!   node_modules/ngxs-reset-plugin
npm ERR!     ngxs-reset-plugin@"*" from the root project
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
```

Please let me know if any more info needed, thanks.

**Comment by armanozak** [comment]
This output shows v3.7.2 has a peer dependency to an Angular version less than 13. I think you should update @ngxs/store to v3.7.3 to support Angular 13.

**Comment by dmitry-salnikov** [comment]
Indeed! I thought the latest version of `@ngxs/store` was 3.7.2 which is mentioned as "Latest release" on it's repo page. Thank you @armanozak for help and the quick response!
